trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Instalar Node.js'

  - script: |
      cd web
      npm install
      npm run build
    displayName: 'Instalar dependências e compilar projeto Vite'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'web/dist'
      ArtifactName: 'DEX-Visualizacao-Painel'
      publishLocation: 'Container'
    displayName: 'Publicar artefato com arquivos do Dashboard'
