trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Instalar Node.js'

  - script: |
      cd web
      npm install
      npm run build
      
      # Cria uma pasta de distribuição contendo a subpasta /dex
      mkdir -p dist-subpath/dex
      cp -r dist/* dist-subpath/dex/
    displayName: 'Instalar dependências, compilar e estruturar subpasta DEX'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/web'
      output_location: 'dist-subpath'
      azure_static_web_apps_api_token: '$(deployment_token)'
    displayName: 'Publicar no Azure Static Web Apps'
