SELECT  IDLAN, IDMOV, NUMERODOCUMENTO AS 'RECIBO', DESCSTATUSLCTO, DATAVENCIMENTO, IDFORMAPAGTO,DESCSTATUSCNAB
,DESCSTATUSEXPORTCONTABILIDADE,CODDEPARTAMENTO,CODCXA, DESCPAGARRECEBER,CODTDO, DATACRIACAO,DATABAIXA,DATACANCELAMENTO,HISTORICO,
VALORORIGINAL, VALORBAIXADO, VALORJUROS,VALORDESCONTO, DATAEMISSAO,DATAPREVBAIXA,CODCFO, VALOROP4BX AS 'TXCARTAO'
,CODAUTORIZACAOVENDA, Descricao_Tipo_Pagamento,CODEVENTOBAIXA,CODCCUSTO

FROM CorporeRM.FLAN 
WHERE 
DATAVENCIMENTO BETWEEN '2025-01-01' AND GETDATE() AND PAGREC = '1'
AND CODTDO NOT IN ('030') -- REEMBOLSOS DIVERSOS (ADIANTAMENTO E DEVOLUÇOES CAIXINHA)
AND CODCXA NOT LIKE '22.420-0' -- FACULDADE
AND HISTORICO NOT LIKE 'Dev. adiantamento  viagem'
AND DESCSTATUSLCTO <> 'Cancelado'



