SELECT  IDLAN, A.IDMOV, NUMERODOCUMENTO AS 'RECIBO', DESCSTATUSLCTO, DATAVENCIMENTO, IDFORMAPAGTO,DESCSTATUSCNAB
,DESCSTATUSEXPORTCONTABILIDADE,A.CODDEPARTAMENTO,CODCXA, DESCPAGARRECEBER,CODTDO, A.DATACRIACAO,DATABAIXA,DATACANCELAMENTO,A.HISTORICO,
VALORORIGINAL, VALORBAIXADO, VALORJUROS,VALORDESCONTO, A.DATAEMISSAO,DATAPREVBAIXA,A.CODCFO, VALOROP4BX AS 'TXCARTAO'
,CODAUTORIZACAOVENDA, Descricao_Tipo_Pagamento,CODEVENTOBAIXA,CODCCUSTO,B.VALORBRUTOORIG,b.CODTMV

FROM CorporeRM.FLAN A
LEFT JOIN CorporeRM.TMOV B ON A.IDMOV =  B.IDMOV
WHERE 
DATAVENCIMENTO BETWEEN '2025-01-01' AND GETDATE() AND PAGREC = '1'
AND CODTDO NOT IN ('030') -- REEMBOLSOS DIVERSOS (ADIANTAMENTO E DEVOLUÇOES CAIXINHA)
AND CODCXA NOT LIKE '22.420-0' -- FACULDADE
AND A.HISTORICO NOT LIKE 'Dev. adiantamento  viagem'
AND DESCSTATUSLCTO <> 'Cancelado'



